name: read file test

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Read file
        id: read_file
        run: |
          {
            echo 'CONTENT<<EOF'
            cat ./main.py
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Echo read 
        run: |
          echo "Contents: $CONTENT"

      - name: Echo secret
        run: |
          echo "Token: ${{secrets.TEST_SECRET_TOKEN}}"